name: Flutter CI Build

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  #----------------------------------------------------
  # Build Android APK
  #----------------------------------------------------
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Upgrade Flutter dependencies
        run: flutter pub upgrade

      - name: Build Flutter APK (Debug)
        run: flutter build apk --debug

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
  
  #----------------------------------------------------
  # Build iOS (Requires macOS runner)
  #----------------------------------------------------
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Pods dependencies
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter iOS (Release - No Code Signing)
        run: flutter build ios --release --no-codesign

      - name: Package .app into .ipa (Unsigned)
        run: |
          APP_BUNDLE_SOURCE="build/ios/iphoneos/Runner.app"
          PAYLOAD_DIR="Payload"
          OUTPUT_IPA_NAME="AurAchieve.ipa"
          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_BUNDLE_SOURCE" "$PAYLOAD_DIR/"
          zip -r "$OUTPUT_IPA_NAME" "$PAYLOAD_DIR"
          rm -rf "$PAYLOAD_DIR"

      - name: Upload Unsigned iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ios-ipa
          path: AurAchieve.ipa
        
      - name: Upload Podfile
        uses: actions/upload-artifact@v4
        with:
          name: Podfile
          path: ios/Podfile